#define CONFIG_USE_FPU 1
#define CONFIG_USE_DEBUG_UART 1
#define CONFIG_OPTION_DBG_UART_2 1
#define CONFIG_DEBUG_UART 2
#define CONFIG_OPTION_DBG_UART_SPEED_115200 1
#define CONFIG_DEBUG_UART_SPEED 115200
